# Support the author by using the funding link below
# Developed and Maintained by Christopher Baier
# Buy Me a Coffee https://buymeacoffee.com/cbaier33

buy_me_a_coffee: cbaier33

# Your generosity means a lot to me to continue the development of open source projects like this.
